### ISSUE TITLE
UnboundLocalError: local variable 'master_addr' referenced before assignment

### ISSUE THREAD

**Issue by breadbrowser** [OpenLMLab/collie#58]
any idea on how to fix it. this is the code i am getting it in.
 #loading model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(token, bos_token='<|startoftext|>', eos_token='<|endoftext|>', pad_token='<|pad|>')

config = CollieConfig.from_pretrained("decapoda-research/llama-7b-hf")
model = LlamaForCausalLM.from_pretrained(model, config=config)

optimizer = AdamW(model.parameters(), lr=learning)

model, optimizer = accelerator.prepare(
     model, optimizer
 )

**Comment by KaiLv69** [comment]
Could you please give more concrete code context e.g. did you use `LlamaForCausalLM` in CoLLiE or HF? Generally, there is no need to use `accelerator` in CoLLiE because we will setup distribution in trainer.
You can refer to the example used here for training translation tasks: https://github.com/OpenLMLab/collie/blob/main/examples/finetune_llama_for_translation.py

**Comment by 00INDEX** [comment]
@breadbrowser Hello. The main reason for your distress is that the program is not started the right way. 
CoLLie is a framework designed for **distributed** training of large models, which means that you should have multiple GPUs and launch your programs in a distributed manner (instead of ``python main.py``). Here are some common distributed startup commands

* ``torchrun --standalone --nproc_per_node 8 main.py`` (Note that the number 8 represents the number of GPUs you want to use, which should be equal to the product of the configured parallel policies in your script ``config.dp_size * config.tp_size * config.pp_size``)
* ``srun --partition=xxx --gres=gpu:8 --ntasks=8 --ntasks-per-node=8 --job-name=xxx --kill-on-bad-exit=1 train.py`` (You can use this command if you are training on a slurm cluster)

**Comment by breadbrowser** [comment]
> Could you please give more concrete code context e.g. did you use `LlamaForCausalLM` in CoLLiE or HF? Generally, there is no need to use `accelerator` in CoLLiE because we will setup distribution in trainer. You can refer to the example used here for training translation tasks: https://github.com/OpenLMLab/collie/blob/main/examples/finetune_llama_for_translation.py

LlamaForCausalLM is from CoLLiE

**Comment by 00INDEX** [comment]
@breadbrowser `accelerator` is not necessary for collie. Once you've initialized your model, you can pass it directly into Trainer:

```python
# main.py
from collie import Trainer, CollieConfig, LlamaForCausalLM
from collie.optim.lomo import Lomo
from transformers import LlamaTokenizer

config = CollieConfig.from_pretrained("decapoda-research/llama-7b-hf")
config.ds_config = {
    "fp16": {
        "enabled": True
    }
}
model = LlamaForCausalLM.from_pretrained("/mnt/petrelfs/zhangshuo/model/llama-7b-hf", config=config)
optimizer = Lomo(model=model, lr=2e-5)
tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf", add_eos_token=True)
tokenizer.pad_token_id = 0
tokenizer.bos_token_id = 1
tokenizer.eos_token_id = 2

inputs = tokenizer("To overfitting this sentence.")

trainer = Trainer(
    model=model,
    config=config,
    optimizer=optimizer,
    train_dataset=[
        ({"input_ids": inputs.input_ids}, {"labels": inputs.input_ids})
    ]
)
trainer.train()
````
Then run:

```bash
torchrun --standalone --nproc_per_node 1 main.py  #because config.dp_size * config.tp_size * config.pp_size == 1
```
Above is a very simple example to train on a sample with one GPU. The core is the command to start, and you should use ``torchrun`` instead of ``python``.

**Comment by breadbrowser** [comment]
> @breadbrowser `accelerator` is not necessary for collie. Once you've initialized your model, you can pass it directly into Trainer:
> 
> ```python
> # main.py
> from collie import Trainer, CollieConfig, LlamaForCausalLM
> from collie.optim.lomo import Lomo
> from transformers import LlamaTokenizer
> 
> config = CollieConfig.from_pretrained("decapoda-research/llama-7b-hf")
> config.ds_config = {
>     "fp16": {
>         "enabled": True
>     }
> }
> model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf", config=config)
> optimizer = Lomo(model=model, lr=2e-5)
> tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf", add_eos_token=True)
> tokenizer.pad_token_id = 0
> tokenizer.bos_token_id = 1
> tokenizer.eos_token_id = 2
> 
> inputs = tokenizer("To overfit this sentence.")
> 
> trainer = Trainer(
>     model=model,
>     config=config,
>     optimizer=optimizer,
>     train_dataset=[
>         ({"input_ids": inputs.input_ids}, {"labels": inputs.input_ids})
>     ]
> )
> trainer.train()
> ```
> 
> Then run:
> 
> ```shell
> torchrun --standalone --nproc_per_node 1 main.py  #because config.dp_size * config.tp_size * config.pp_size == 1
> ```
> 
> Above is a very simple example to train on a sample with one GPU. The core is the command to start, and you should use `torchrun` instead of `python`.
ok

**Comment by breadbrowser** [comment]
> @breadbrowser `accelerator` is not necessary for collie. Once you've initialized your model, you can pass it directly into Trainer:
> 
> ```python
> # main.py
> from collie import Trainer, CollieConfig, LlamaForCausalLM
> from collie.optim.lomo import Lomo
> from transformers import LlamaTokenizer
> 
> config = CollieConfig.from_pretrained("decapoda-research/llama-7b-hf")
> config.ds_config = {
>     "fp16": {
>         "enabled": True
>     }
> }
> model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf", config=config)
> optimizer = Lomo(model=model, lr=2e-5)
> tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf", add_eos_token=True)
> tokenizer.pad_token_id = 0
> tokenizer.bos_token_id = 1
> tokenizer.eos_token_id = 2
> 
> inputs = tokenizer("To overfit this sentence.")
> 
> trainer = Trainer(
>     model=model,
>     config=config,
>     optimizer=optimizer,
>     train_dataset=[
>         ({"input_ids": inputs.input_ids}, {"labels": inputs.input_ids})
>     ]
> )
> trainer.train()
> ```
> 
> Then run:
> 
> ```shell
> torchrun --standalone --nproc_per_node 1 main.py  #because config.dp_size * config.tp_size * config.pp_size == 1
> ```
> 
> Above is a very simple example to train on a sample with one GPU. The core is the command to start, and you should use `torchrun` instead of `python`.

how would that work for a csv?
